### ISSUE TITLE
CARIC at CDC 2023: CMake Error:Could not find a package configuration file provided by "tcc" during catkin build

### ISSUE THREAD

**Issue by KayatoDQY** [brytsknguyen/caric_mission#1]
## Question:
When building the CDC 2023 simulation environment, according to the official website (https://ntu-aris.github.io/caric/), the following error occurs when executing the ` catkin build ` command
```
___________________________________________________________________________________________________________________________
Errors     << caric_mission:check /home/dqy/ws_caric/logs/caric_mission/build.check.003.log
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "tcc" with any of
  the following names:

    tccConfig.cmake
    tcc-config.cmake

  Add the installation prefix of "tcc" to CMAKE_PREFIX_PATH or set "tcc_DIR"
  to a directory containing one of the above files.  If "tcc" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:9 (find_package)


make: *** [Makefile:1764: cmake_check_build_system] Error 1
cd /home/dqy/ws_caric/build/caric_mission; catkin build --get-env caric_mission | catkin env -si  /usr/bin/make cmake_check_build_system; cd -

...........................................................................................................................
```
## Solution:
It seems that this ` tcc ` package is not needed in CARIC at CDC 2023 simulation.
The repository was later modified to fix the wrong content. So you just need to re-pull on the master branch, or delete the package and re-clone it.
```
cd ~/ws_caric/src/caric_mission
git branch #Check if it is the master branch
git checkout master #switch to master branch
git pull
cd ~/ws_caric
catkin build
```
or re-clone
```
~/ws_caric/src
rm -r caric_mission
git clone https://github.com/ntu-aris/caric_mission.git
cd ~/ws_caric
catkin build
```
Thanks to the author for answering.

**Comment by brytsknguyen** [comment]
Hi @KayatoDQY,

Thanks for reporting the issue. The "tcc" package was later changed to "unicon". The unicon package is mentioned in the [installation guide](https://ntu-aris.github.io/caric/#42-install-the-caric-packages).

This repository https://github.com/brytsknguyen/caric_mission is deprecated. All latest updates are at https://github.com/ntu-aris/caric_mission. I will turn this repository to private to avoid the confusion.

Regards,
Thien-Minh
